import {
	ORDER_STATUS,
	PAYMENT_STATUS,
	DELIVERY_STATUS,
} from "@/shared/contracts/order/order.contract";
import { COLORS } from "@/shared/components/common/color-badge";

export const ORDER_STATUS_COLOR: Record<
	ORDER_STATUS,
	(typeof COLORS)[keyof typeof COLORS]
> = {
	[ORDER_STATUS.NEW]: COLORS.BLUE,
	[ORDER_STATUS.SEEN]: COLORS.GRAY,
	[ORDER_STATUS.CONTACTED]: COLORS.PURPLE,
	[ORDER_STATUS.CONFIRMED]: COLORS.YELLOW,
	[ORDER_STATUS.PROCESSING]: COLORS.ORANGE,
	[ORDER_STATUS.COMPLETED]: COLORS.GREEN,
	[ORDER_STATUS.CANCELLED]: COLORS.RED,
	[ORDER_STATUS.IGNORED]: COLORS.GRAY,
};

export const PAYMENT_STATUS_COLOR: Record<
	PAYMENT_STATUS,
	(typeof COLORS)[keyof typeof COLORS]
> = {
	[PAYMENT_STATUS.UNPAID]: COLORS.RED,
	[PAYMENT_STATUS.PARTIAL]: COLORS.YELLOW,
	[PAYMENT_STATUS.PAID]: COLORS.GREEN,
	[PAYMENT_STATUS.REFUNDED]: COLORS.ORANGE,
};

export const DELIVERY_STATUS_COLOR: Record<
	DELIVERY_STATUS,
	(typeof COLORS)[keyof typeof COLORS]
> = {
	[DELIVERY_STATUS.PENDING]: COLORS.GRAY,
	[DELIVERY_STATUS.PREPARING]: COLORS.YELLOW,
	[DELIVERY_STATUS.SHIPPED]: COLORS.BLUE,
	[DELIVERY_STATUS.DELIVERED]: COLORS.GREEN,
	[DELIVERY_STATUS.RETURNED]: COLORS.ORANGE,
};
