export type TCountry = {
	name: string;
	flag: string;
	code: string;
	iso: string;
};

export const COUNTRY_CODES: TCountry[] = [
	{ name: "Afghanistan", flag: "🇦🇫", code: "+93", iso: "AF" },
	{ name: "Albania", flag: "🇦🇱", code: "+355", iso: "AL" },
	{ name: "Algeria", flag: "🇩🇿", code: "+213", iso: "DZ" },
	{ name: "Argentina", flag: "🇦🇷", code: "+54", iso: "AR" },
	{ name: "Australia", flag: "🇦🇺", code: "+61", iso: "AU" },
	{ name: "Austria", flag: "🇦🇹", code: "+43", iso: "AT" },
	{ name: "Azerbaijan", flag: "🇦🇿", code: "+994", iso: "AZ" },
	{ name: "Bahrain", flag: "🇧🇭", code: "+973", iso: "BH" },
	{ name: "Bangladesh", flag: "🇧🇩", code: "+880", iso: "BD" },
	{ name: "Belarus", flag: "🇧🇾", code: "+375", iso: "BY" },
	{ name: "Belgium", flag: "🇧🇪", code: "+32", iso: "BE" },
	{ name: "Bolivia", flag: "🇧🇴", code: "+591", iso: "BO" },
	{ name: "Bosnia", flag: "🇧🇦", code: "+387", iso: "BA" },
	{ name: "Brazil", flag: "🇧🇷", code: "+55", iso: "BR" },
	{ name: "Bulgaria", flag: "🇧🇬", code: "+359", iso: "BG" },
	{ name: "Cambodia", flag: "🇰🇭", code: "+855", iso: "KH" },
	{ name: "Cameroon", flag: "🇨🇲", code: "+237", iso: "CM" },
	{ name: "Canada", flag: "🇨🇦", code: "+1", iso: "CA" },
	{ name: "Chile", flag: "🇨🇱", code: "+56", iso: "CL" },
	{ name: "China", flag: "🇨🇳", code: "+86", iso: "CN" },
	{ name: "Colombia", flag: "🇨🇴", code: "+57", iso: "CO" },
	{ name: "Croatia", flag: "🇭🇷", code: "+385", iso: "HR" },
	{ name: "Czech Republic", flag: "🇨🇿", code: "+420", iso: "CZ" },
	{ name: "Denmark", flag: "🇩🇰", code: "+45", iso: "DK" },
	{ name: "Ecuador", flag: "🇪🇨", code: "+593", iso: "EC" },
	{ name: "Egypt", flag: "🇪🇬", code: "+20", iso: "EG" },
	{ name: "Ethiopia", flag: "🇪🇹", code: "+251", iso: "ET" },
	{ name: "Finland", flag: "🇫🇮", code: "+358", iso: "FI" },
	{ name: "France", flag: "🇫🇷", code: "+33", iso: "FR" },
	{ name: "Georgia", flag: "🇬🇪", code: "+995", iso: "GE" },
	{ name: "Germany", flag: "🇩🇪", code: "+49", iso: "DE" },
	{ name: "Ghana", flag: "🇬🇭", code: "+233", iso: "GH" },
	{ name: "Greece", flag: "🇬🇷", code: "+30", iso: "GR" },
	{ name: "Hong Kong", flag: "🇭🇰", code: "+852", iso: "HK" },
	{ name: "Hungary", flag: "🇭🇺", code: "+36", iso: "HU" },
	{ name: "India", flag: "🇮🇳", code: "+91", iso: "IN" },
	{ name: "Indonesia", flag: "🇮🇩", code: "+62", iso: "ID" },
	{ name: "Iran", flag: "🇮🇷", code: "+98", iso: "IR" },
	{ name: "Iraq", flag: "🇮🇶", code: "+964", iso: "IQ" },
	{ name: "Ireland", flag: "🇮🇪", code: "+353", iso: "IE" },
	{ name: "Israel", flag: "🇮🇱", code: "+972", iso: "IL" },
	{ name: "Italy", flag: "🇮🇹", code: "+39", iso: "IT" },
	{ name: "Japan", flag: "🇯🇵", code: "+81", iso: "JP" },
	{ name: "Jordan", flag: "🇯🇴", code: "+962", iso: "JO" },
	{ name: "Kazakhstan", flag: "🇰🇿", code: "+7", iso: "KZ" },
	{ name: "Kenya", flag: "🇰🇪", code: "+254", iso: "KE" },
	{ name: "Kuwait", flag: "🇰🇼", code: "+965", iso: "KW" },
	{ name: "Lebanon", flag: "🇱🇧", code: "+961", iso: "LB" },
	{ name: "Libya", flag: "🇱🇾", code: "+218", iso: "LY" },
	{ name: "Malaysia", flag: "🇲🇾", code: "+60", iso: "MY" },
	{ name: "Mexico", flag: "🇲🇽", code: "+52", iso: "MX" },
	{ name: "Morocco", flag: "🇲🇦", code: "+212", iso: "MA" },
	{ name: "Myanmar", flag: "🇲🇲", code: "+95", iso: "MM" },
	{ name: "Nepal", flag: "🇳🇵", code: "+977", iso: "NP" },
	{ name: "Netherlands", flag: "🇳🇱", code: "+31", iso: "NL" },
	{ name: "New Zealand", flag: "🇳🇿", code: "+64", iso: "NZ" },
	{ name: "Nigeria", flag: "🇳🇬", code: "+234", iso: "NG" },
	{ name: "Norway", flag: "🇳🇴", code: "+47", iso: "NO" },
	{ name: "Oman", flag: "🇴🇲", code: "+968", iso: "OM" },
	{ name: "Pakistan", flag: "🇵🇰", code: "+92", iso: "PK" },
	{ name: "Palestine", flag: "🇵🇸", code: "+970", iso: "PS" },
	{ name: "Paraguay", flag: "🇵🇾", code: "+595", iso: "PY" },
	{ name: "Peru", flag: "🇵🇪", code: "+51", iso: "PE" },
	{ name: "Philippines", flag: "🇵🇭", code: "+63", iso: "PH" },
	{ name: "Poland", flag: "🇵🇱", code: "+48", iso: "PL" },
	{ name: "Portugal", flag: "🇵🇹", code: "+351", iso: "PT" },
	{ name: "Qatar", flag: "🇶🇦", code: "+974", iso: "QA" },
	{ name: "Romania", flag: "🇷🇴", code: "+40", iso: "RO" },
	{ name: "Russia", flag: "🇷🇺", code: "+7", iso: "RU" },
	{ name: "Saudi Arabia", flag: "🇸🇦", code: "+966", iso: "SA" },
	{ name: "Senegal", flag: "🇸🇳", code: "+221", iso: "SN" },
	{ name: "Serbia", flag: "🇷🇸", code: "+381", iso: "RS" },
	{ name: "Singapore", flag: "🇸🇬", code: "+65", iso: "SG" },
	{ name: "South Africa", flag: "🇿🇦", code: "+27", iso: "ZA" },
	{ name: "South Korea", flag: "🇰🇷", code: "+82", iso: "KR" },
	{ name: "Spain", flag: "🇪🇸", code: "+34", iso: "ES" },
	{ name: "Sri Lanka", flag: "🇱🇰", code: "+94", iso: "LK" },
	{ name: "Sudan", flag: "🇸🇩", code: "+249", iso: "SD" },
	{ name: "Sweden", flag: "🇸🇪", code: "+46", iso: "SE" },
	{ name: "Switzerland", flag: "🇨🇭", code: "+41", iso: "CH" },
	{ name: "Syria", flag: "🇸🇾", code: "+963", iso: "SY" },
	{ name: "Taiwan", flag: "🇹🇼", code: "+886", iso: "TW" },
	{ name: "Tanzania", flag: "🇹🇿", code: "+255", iso: "TZ" },
	{ name: "Thailand", flag: "🇹🇭", code: "+66", iso: "TH" },
	{ name: "Tunisia", flag: "🇹🇳", code: "+216", iso: "TN" },
	{ name: "Turkey", flag: "🇹🇷", code: "+90", iso: "TR" },
	{ name: "Uganda", flag: "🇺🇬", code: "+256", iso: "UG" },
	{ name: "Ukraine", flag: "🇺🇦", code: "+380", iso: "UA" },
	{ name: "United Arab Emirates", flag: "🇦🇪", code: "+971", iso: "AE" },
	{ name: "United Kingdom", flag: "🇬🇧", code: "+44", iso: "GB" },
	{ name: "United States", flag: "🇺🇸", code: "+1", iso: "US" },
	{ name: "Uruguay", flag: "🇺🇾", code: "+598", iso: "UY" },
	{ name: "Uzbekistan", flag: "🇺🇿", code: "+998", iso: "UZ" },
	{ name: "Venezuela", flag: "🇻🇪", code: "+58", iso: "VE" },
	{ name: "Vietnam", flag: "🇻🇳", code: "+84", iso: "VN" },
	{ name: "Yemen", flag: "🇾🇪", code: "+967", iso: "YE" },
	{ name: "Zimbabwe", flag: "🇿🇼", code: "+263", iso: "ZW" },
];

export const COUNTRY_CURRENCIES = [
	"AED",
	"AFN",
	"ALL",
	"ARS",
	"AUD",
	"AZN",
	"BAM",
	"BDT",
	"BGN",
	"BHD",
	"BOB",
	"BRL",
	"BYN",
	"CAD",
	"CHF",
	"CLP",
	"CNY",
	"COP",
	"CZK",
	"DKK",
	"DZD",
	"EGP",
	"ETB",
	"EUR",
	"GBP",
	"GEL",
	"GHS",
	"HKD",
	"HUF",
	"IDR",
	"ILS",
	"INR",
	"IQD",
	"IRR",
	"JPY",
	"JOD",
	"KES",
	"KHR",
	"KRW",
	"KWD",
	"KZT",
	"LBP",
	"LKR",
	"LYD",
	"MAD",
	"MMK",
	"MXN",
	"MYR",
	"NGN",
	"NOK",
	"NPR",
	"NZD",
	"OMR",
	"PEN",
	"PHP",
	"PKR",
	"PLN",
	"PYG",
	"QAR",
	"RON",
	"RSD",
	"RUB",
	"SAR",
	"SDG",
	"SEK",
	"SGD",
	"SYP",
	"THB",
	"TND",
	"TRY",
	"TWD",
	"TZS",
	"UAH",
	"UGX",
	"USD",
	"UYU",
	"UZS",
	"VES",
	"VND",
	"XAF",
	"XOF",
	"YER",
	"ZAR",
	"ZWG",
];
